    <div class="px-4 py-5 my-5 text-center">
        <h1 class="display-5 fw-bold text-body-emphasis">Autos de Lujo Exclusivos</h1>
        <div class="col-lg-6 mx-auto">
            <p class="lead mb-4">Descubre la excelencia automotriz con nuestra exclusiva colección de autos de lujo. Experimenta un rendimiento, artesanía y estilo inigualables.</p>
            <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
                <a href="showVehicles" class="btn btn-primary btn-lg px-4 gap-3">Explorar Vehículos</a>
                <a href="showCategories" class="btn btn-primary btn-lg px-4 gap-3">Explorar Modelos</a>
            </div>
        </div>
    </div>
