<section class="container">
        <h3>Agregar un modelo</h3>
        <form action="addCategory" method="POST">
            <!-- Nombre -->
            <div class="form-group col-lg-2">
                <label for="nombre"></label>
                <input type="text" class="form-control" id="nombre" name="nombre" placeholder="Nombre">
            </div>
            <!-- Año -->
            <div class="form-group col-lg-2">
                <label for="Anio"></label>
                <input type="number" min="0" class="form-control" id="anio" name="anio" placeholder="Año">
            </div>
            <!-- Capacidad -->
            <div class="form-group col-lg-2">
                <label for="capacidad"></label>
                <input type="number" min="0" class="form-control" id="capacidad" name="capacidad" placeholder="Asientos">
            </div>
            <!-- Combustible -->
            <div class="form-group col-lg-2">
                <label for="combustible"></label>
                <input type="text" class="form-control" id="combustible" name="combustible" placeholder="Combustible">
            </div>
            <!-- Submit -->
            <div class="form-group col-lg-2">
                <label for="submit"></label>
                <input type="submit" class="form-control" id="submit" name="submit" value="Agregar">
            </div>
        </form>
        <p><?= $message ?></p>
    </section>