<section class="container"> 
        <h3>Actualizar un vehículo</h3>
        <form action="updateVehicle" method="POST">
            <!-- Id (Oculto) -->
            <input type="hidden" id="id" name="id" value="<?= $vehicle[0]["AutoId"] ?>">
            <!-- Marca -->
            <div class="form-group col-lg-2">
                <label for="marca"></label>
                <input type="text" class="form-control" id="marca" name="marca" placeholder="Marca" value="<?= $vehicle[0]["Marca"] ?>">
            </div>
            <!-- Modelo -->
            <div class="form-group col-lg-2">
                <label for="modelo"></label>
                <select class="form-control" id="modelo" name="modelo" value="<?= $vehicle[0]["Id"] ?>">
                <?php foreach ($categories as $category): ?>
                    <?php if ($category["Id"] == $vehicle[0]["ModeloId"]): ?>
                        <option value="<?= $category["Id"] ?>" selected><?= $category["Nombre"] ?></option>
                    <?php else: ?>
                        <option value="<?= $category["Id"] ?>"><?= $category["Nombre"] ?></option>
                    <?php endif ?>
                <?php endforeach ?>>
                </select>
            </div>
            <!-- Kilometraje -->
            <div class="form-group col-lg-2">
                <label for="kilometraje"></label>
                <input type="number" min="0" class="form-control" id="kilometraje" name="kilometraje" placeholder="Kms" value="<?= $vehicle[0]["Kilometraje"] ?>">
            </div>
            <!-- Precio -->
            <div class="form-group col-lg-2">
                <label for="precio"></label>
                <input type="number" step="0.01" min="0.01" class="form-control" id="precio" name="precio" placeholder="Precio" value="<?= $vehicle[0]["Precio"] ?>">
            </div>
            <!-- Submit -->
            <div class="form-group col-lg-2">
                <label for="submit"></label>
                <input type="submit" class="form-control" id="submit" name="submit" value="Actualizar">
            </div>
        </form>
        <p><?= $message ?></p>
    </section>