<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Iniciar sesión en Lux Cars</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body class="d-flex align-items-center px-5 py-4 bg-body-tertiary">
    <main class="form-signin w-50 m-auto">
        <div class="container"><?= $message ?></div>
        <form action="login" method="POST">
            <h1 class="h3 mb-3 fw-normal">Bienvenido</h1>

            <div class="form-floating">
            <input type="text" class="form-control" id="Nombre" name="Nombre" placeholder="Nombre">
            <label for="Nombre">Nombre de Usuario</label>
            </div>
            <div class="form-floating">
            <input type="password" class="form-control" id="Contrasenia" name="Contrasenia" placeholder="Password">
            <label for="Contrasenia">Contraseña</label>
            </div>

            <button class="btn btn-primary w-100 py-2" type="submit">Iniciar sesión</button>
        </form>
        <a href="home" class="btn btn-secondary">Volver a la página de inicio</a>
    </main>
</body>