    <section class="container">
        <h3>Agregar un vehículo</h3>
        <form action="addVehicle" method="POST">
            <!-- Marca -->
            <div class="form-group col-lg-2">
                <label for="marca"></label>
                <input type="text" class="form-control" id="marca" name="marca" placeholder="Marca">
            </div>
            <!-- Modelo -->
            <div class="form-group col-lg-2">
                <label for="modelo"></label>
                <select class="form-control" id="modelo" name="modelo" placeholder="Modelo">
                <?php foreach ($categories as $category): ?>
                    <option value="<?= $category["Id"] ?>"><?= $category["Nombre"] ?></option>
                <?php endforeach ?>>
                </select>
            </div>
            <!-- Kilometraje -->
            <div class="form-group col-lg-2">
                <label for="kilometraje"></label>
                <input type="number" min="0" class="form-control" id="kilometraje" name="kilometraje" placeholder="Kms">
            </div>
            <!-- Precio -->
            <div class="form-group col-lg-2">
                <label for="precio"></label>
                <input type="number" step="0.01" min="0.01" class="form-control" id="precio" name="precio" placeholder="Precio">
            </div>
            <!-- Submit -->
            <div class="form-group col-lg-2">
                <label for="submit"></label>
                <input type="submit" class="form-control" id="submit" name="submit" value="Agregar">
            </div>
        </form>
        <p><?= $message ?></p>
    </section>