    <!-- Formulario de vehículos -->
    <section class="container px-1">
        <form id="filterForm" class="row row-cols-lg-auto">
            <div class="form-group col-lg-1">
                <label for="marca"></label>
                <input type="text" class="form-control" id="marca" name="marca" placeholder="Marca">
            </div>
            <div class="form-group col-lg-2">
                <label for="modelo"></label>
                <input type="text" class="form-control" id="modelo" name="modelo" placeholder="Modelo">
            </div>
            <div class="form-group col-lg-1">
                <label for="anio"></label>
                <input type="number" class="form-control" id="anio" name="anio" placeholder="Año">
            </div>
            <div class="form-group col-lg-1">
                <label for="kilometraje"></label>
                <input type="number" class="form-control" id="kilometraje" name="kilometraje" placeholder="Kms">
            </div>
            <div class="form-group col-lg-2">
                <label for="capacidad"></label>
                <input type="number" class="form-control" id="capacidad" name="capacidad" placeholder="Nro de asientos">
            </div>
            <div class="form-group col-lg-2">
                <label for="combustible"></label>
                <input type="text" class="form-control" id="combustible" name="combustible" placeholder="Combustible">
            </div>
            <div class="form-group col-lg-2">
                <label for="precio"></label>
                <input type="number" class="form-control" id="precio" name="precio" placeholder="Precio">
            </div>
            <div class="form-group col-lg-1">
                <label for="submit"></label>
                <input type="submit" class="form-control" id="submit" name="submit" value="Filtrar">
            </div>
        </form>
    </section>