            <div class="col">
                <div class="card shadow-sm">
                    <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false">
                        <rect width="100%" height="100%" fill="#55595c"></rect><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text>
                    </svg>
                    <div class="card-body">
                        <p class="card-text"><?= $vehicle['Marca']." ".$vehicle['ModeloNombre']; ?></p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a href="<?= "vehicle?id=".$vehicle['AutoId'] ?>" class="btn btn-sm btn-outline-secondary">Ver</a>                           
                                <a href="#" class="btn btn-sm btn-outline-secondary">Editar</a>                           
                            </div>
                            <small class="text-body-secondary"><?= "$".$vehicle['Precio']." USD"; ?></small>
                        </div>
                    </div>
                </div>
            </div>
