<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
    <header class="d-flex flex-wrap justify-content-center px-3 py-3 mb-4 border-bottom">
        <a href="home" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto link-body-emphasis text-decoration-none">
            <span class="fs-4">Lux Cars</span>
        </a>

        <ul class="nav nav-pills">
            <li class="nav-item"><a href="showVehicles" class="nav-link">Listar autos</a></li>
            <li class="nav-item"><a href="logIn" class="nav-link">Iniciar sesión</a></li>
        </ul>
    </header>
